name: Schedule

on: 
  schedule:
    - cron: '0 0 14 7 *'
  workflow_dispatch:

jobs: 
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Update README
        run: |
          node update-readme.js
      
      - name: Commit and Push
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update README.md"
          git push
